# Generated by Django 4.2.6 on 2025-10-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('display_name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['distance_km'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(default='Indonesia', max_length=120)),
                ('venue', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registration_deadline', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('popularity_score', models.PositiveIntegerField(default=0)),
                ('participant_limit', models.PositiveIntegerField(default=0)),
                ('registered_count', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('banner_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='events', to='events.eventcategory')),
            ],
            options={
                'ordering': ['start_date', 'title'],
                'indexes': [models.Index(fields=['status'], name='events_even_status_5709b6_idx'), models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx'), models.Index(fields=['city'], name='events_even_city_533bd7_idx')],
            },
        ),
    ]
