# Generated by Django 4.2.6 on 2025-12-21 10:00

from django.db import migrations


def seed_event_categories(apps, schema_editor):
    EventCategory = apps.get_model("events", "EventCategory")
    defaults = [
        {"name": "5k", "display_name": "5K", "distance_km": 5},
        {"name": "10k", "display_name": "10K", "distance_km": 10},
        {"name": "half-marathon", "display_name": "21K Half Marathon", "distance_km": 21.1},
        {"name": "marathon", "display_name": "42K Marathon", "distance_km": 42.2},
        {"name": "ultra-marathon", "display_name": "Ultra Marathon", "distance_km": 50},
    ]

    for payload in defaults:
        EventCategory.objects.get_or_create(
            name=payload["name"],
            defaults={
                "display_name": payload["display_name"],
                "distance_km": payload["distance_km"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_registration_open_date"),
    ]

    operations = [
        migrations.RunPython(seed_event_categories, migrations.RunPython.noop),
    ]
