# Generated by Django 5.2.7 on 2025-10-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userracehistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('registered', 'Registered'), ('completed', 'Completed'), ('dnf', 'Did Not Finish'), ('dns', 'Did Not Start'), ('upcoming', 'Upcoming')], default='pending', max_length=20),
        ),
    ]
