# Generated by Django 4.2.6 on 2025-10-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='events.event')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('document_url', models.URLField()),
                ('document_type', models.CharField(choices=[('gpx', 'GPX Route'), ('guide', 'Race Guide'), ('brochure', 'Brochure'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_by', models.CharField(default='Organizing Committee', max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='events.event')),
            ],
            options={
                'ordering': ['document_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AidStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kilometer_marker', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supplies', models.CharField(help_text='Key supplies provided (water, gels, medical, etc.)', max_length=200)),
                ('is_medical', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_stations', to='events.event')),
            ],
            options={
                'ordering': ['kilometer_marker'],
            },
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('elevation_gain', models.PositiveIntegerField(default=0, help_text='Elevation gain in meters.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments', to='events.event')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('event', 'order')},
            },
        ),
    ]
